version: '3'

volumes:
  local_redis: {}

services:
  rust:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/work
  redis:
    image: redis:7.0-rc2
    volumes:
      - local_redis:/data
